baseurl = "https://54696d21.github.io/"
title = "54696d21's blog"
author = "54696d21"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "54696d21's blog"
  faviconfile = "static/images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/54696d21"
    weight = 3
[[menu.primary]]
    name = "Twitter"
    url = "https://twitter.com/54696d21"
    weight = 4
# [[menu.primary]]
#     name = "Subscribe"
#     url = "/index.xml"
#     weight = 5
